version: '3.7'
services:
  flask:
     build: flask
     container_name: web
     restart: always
     ports:
       - 5000:5000
     environment:
       - DEBUG=0
     networks:
       - flask_network
  nginx:
      build: nginx
      restart: always
      container_name: proxy
      ports:
        - 80:80
      networks:
        - flask_network
  postgres:
      image: postgres:13
      container_name: db
      restart: always
      ports:
        - 5432:5432
      networks:
        - flask_network
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=dbPassword
        - POSTGRES_DB=todo
      volumes:
        - postgres_data:/var/lib/postgresql/data
networks:
  flask_network:

volumes:
  postgres_data: