version: '3.7'
services:
  flask:
     build: flask
     container_name: web
     restart: always
     ports:
       - 5000:5000
     environment:
       - DEBUG=0
     networks:
       - flask_network

networks:
  flask_network:

volumes:
  postgres_data:
