version: '3.7'
services:
  postgres:
      image: postgres:13
      container_name: db
      restart: always
      ports:
        - 5433:5433
      networks:
        - flask_network
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=dbPassword
        - POSTGRES_DB=todo
      volumes:
        - postgres_data:/var/lib/postgresql/data
networks:
  flask_network:

volumes:
  postgres_data:
